version: "3"
services:
  api:
    build: components/core/
    container_name: api
    ports:
      - 5000:5000
    links:
      - db
      - aria2c
    environment:
      BASSA_DB_NAME: Bassa
      BASSA_DB_USERNAME: bassa
      BASSA_DB_PASSWORD: bassa@1234
    labels:
      com.example.description: "Docker container for Bassa UI"

  web:
    build: ui/
    container_name: web
    ports:
      - 3000:3000
    links:
      - db
    labels:
      com.example.description: "Docker container for Bassa backend"

  aria2c:
    build: components/core/aria2c/
    container_name: aria2c
    links:
      - db
    ports:
      - 6800:6800
    restart: always

  db:
    image: mariadb
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
    #  - ./.docker/volumes/mysql:/docker-entrypoint-initdb.d
    #  - ./db_schema/:/tmp/schema
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bassa@1234
      MYSQL_DATABASE: Bassa
      MYSQL_USER: bassa
      MYSQL_PASSWORD: bassa@1234

volumes:
  data-volume:
